export const BLOCK_LIMIT = 600;
export const INTERNAL_RISK_LIMIT = 100;
export const INTERNAL_TO_INTERNAL_RISK_LIMIT = 300;
export const REJECTION_PENALTY = 0.15;
export const INTERNAL_TO_INTERNAL_REJECTION_PENALTY = 0.1;